queue_rules:
  - name: default
    conditions: []

pull_request_rules:
  - name: automatic merge on approval when the title does not contain “WIP” (ignoring case)
    conditions:
        - and:
            - "#approved-reviews-by>=1"
            - or:
              - -title~=(?i)wip
              - "files=1"
    actions:
      merge:
        method: merge