queue_rules:
  - name: default
    conditions: ["files>=1"]

  - name: coin-coin
    conditions: []

pull_request_rules:
  - name: Generic rule
    conditions:
      - -title~=(?i)wip
    actions:
      queue:
        name: default
        
  - name: automatic merge on approval when the title does not contain “WIP” (ignoring case)
    conditions:
            - "#approved-reviews-by>=1"
            - -title~=(?i)wip
            - "files=1"
    actions:
      comment:
        message: "@{{author}} this pull request is waiting for approuval"
      label:
        add:
          - "To do"
        
  - name: mergue using the merge queue
    conditions:
      - "#approved-reviews-by>=1"
      - base=master
      - "#files>=1"
      - label!=urgent
    actions:
      queue:
        name: default

  - name: automatic update for PR marked as “To do“
    conditions:
      - "#approved-reviews-by>=1"
      - -conflict
      - -draft
      - label="To do"
    actions:
      update:
      
  - name: warn on conflicts
    conditions:
      - conflict
    actions:
      queue:
        name: coin-coin
      comment:
        message: "@{{author}} this pull request is now in conflict 😩"
      label:
        add:
          - conflict

  - name: remove conflict label if not needed
    conditions:
      - "#approved-reviews-by>=1"
      - -conflict
    actions:
      label:
        remove:
          - conflict
