queue_rules:
  - name: default
    conditions: []

pull_request_rules:
  - name: automatic merge on approval when the title does not contain “WIP” (ignoring case)
    conditions:
            - "#approved-reviews-by>=1"
            - -title~=(?i)wip
            - "files=1"
    actions:
      merge:
        method: merge
        
  - name: mergue using the merge queue
    conditions:
      - base=master
      - "#files>=1"
      - label!=urgent
    actions:
      queue:
        name: default

  - name: automatic update for PR marked as “To do“
    conditions:
      - "#approved-reviews-by>=1"
      - -conflict
      - -draft
      - label="To do"
    actions:
      update:
